name: Ubuntu SSH Sandbox with Tailscale
# SSH: runner:6MonkeysRLooking^

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    # Allows external webhook trigger
    repository_dispatch:
        types: [ubuntu-ssh-tailscale]

# You can use the following syntax to disable permissions for all of the available permissions:
permissions: {}

# concurrency:
#     # Only one workflow can run at a time
#     group: ${{ github.workflow }}
#     cancel-in-progress: true # Cancel previous runs

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "sandbox"
    sandbox:
        # The type of runner that the job will run on
        runs-on: ubuntu-24.04
        # This is a hard limit. 360 is the maximum allowed by GitHub.
        timeout-minutes: 360

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            # - uses: actions/checkout@v4

            - name: Setup
              run: |
                  # Change password
                  echo "runner:6MonkeysRLooking^" | sudo chpasswd
                  # Install SSH
                  sudo apt-get update
                  sudo apt-get install openssh-server
                  sudo systemctl enable --now ssh

            - name: Tailscale
              uses: tailscale/github-action@v3
              with:
                  oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                  tags: tag:ci
                  # Tailscale SSH feature does not need openssh-server or user password, it's controlled by ACL
                  args: --advertise-exit-node --ssh
                  hostname: gha-ubuntu-sandbox
                  version: latest

            # Should be runner
            - name: whoami
              run: whoami

            # Each job in a workflow can run for up to 6 hours of execution time.
            # If a job reaches this limit, the job is terminated and fails.
            - name: Sleep
              run: |
                  echo -e "#!/bin/bash\n\ntouch /tmp/stop_sleeping_step_confirmed" | sudo tee /home/runner/shutdown_confirmed.sh
                  sudo chmod +x /home/runner/shutdown_confirmed.sh
                  echo "Sleeping..."
                  while [ ! -e /tmp/stop_sleeping_step_confirmed ]; do
                      sleep 5
                  done
